### ISSUE TITLE
memory management

### ISSUE THREAD

**Issue by mlubin** [oxfordcontrol/OSQP.jl#2]
This wrapper is vulnerable to the same sort of memory corruption that we [just fixed](https://discourse.julialang.org/t/memory-corruption-bugs-in-ecos-jl-and-scs-jl) in ECOS.jl and SCS.jl (not your fault for copying them).

For example:
-  [`Ccsc`](https://github.com/oxfordcontrol/OSQP.jl/blob/ae25317516937f2f074aaaddc3ef598b9873755f/src/types.jl#L22) keeps pointers to arrays that could be freed at any time. 
- `pointer([Pcsc])` [here](https://github.com/oxfordcontrol/OSQP.jl/blob/ae25317516937f2f074aaaddc3ef598b9873755f/src/types.jl#L86) is bad. The array `[Pscs]` can be garbage collected at any moment after the `pointer` call.

In general, you have to make sure that you maintain a reference to the Julia object for at least as long as the `Ptr` is used.

**Comment by bstellato** [comment]
Thanks for the letting me know! I cannot fix it right now, but I will have a look in the next weeks.
