### ISSUE TITLE
Wrong attribute in processdualstart()

### ISSUE THREAD

**Issue by migarstka** [oxfordcontrol/OSQP.jl#40]
I think I spotted a bug in the `processdualstart()` function of the MOIWrapper.

The line:

 https://github.com/oxfordcontrol/OSQP.jl/blob/8dd46b5a7c8955ae41cf8464295825801946e939/src/MOI_wrapper.jl#L369

should be replaced with
```julia
if attr isa MOI.ConstraintDualStart
```

**Comment by blegat** [comment]
Indeed, want to make a PR ?

**Comment by migarstka** [comment]
Addressed in #41
