### ISSUE TITLE
Constraints relaxation

### ISSUE THREAD

**Issue by jebouchat** [oxfordcontrol/OSQP.jl#46]
Hello!

I have an optimization problem with variables belonging to [0,1] and an objective whose convexity depends on the non-negativity of the aforementioned variables. Unfortunately, it seems that the solver relaxes the constraints resulting in an error since the objective becomes non-convex.

Is there a way to prevent this from happening? to force the solver to respect some constraints?

**Comment by bstellato** [comment]
OSQP is proven to work only with positive semidefinite matrix `P`. In other cases it can fail. Could you please write a minimal working example that we could run?

In many cases like yours (not all!) you can reformulate your problem to avoid nonconvexities.

**Comment by bstellato** [comment]
I would close this due to inactivity. Feel free to reopen it here or in the main OSQP repo if you have more concerns. Since it is a formulation question, I would suggest you to use the OSQP forum.
