### ISSUE TITLE
Error when install.

### ISSUE THREAD

**Issue by QiayuanLiao** [oxfordcontrol/OSQP.jl#57]
My conputer run Mac OS 10.14.5.
I cann't install OSQP when run 
`julia> Pkg.build("OSQP")`
the output is: 
Building OSQP → `~/.juliapro/JuliaPro_v1.1.1.1/packages/OSQP/FaA6U/deps/build.log`
┌ Error: Error building `OSQP`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0     34      0  0:00:01  0:00:01 --:--:--    34
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0      2      0  0:00:32  0:00:21  0:00:11    14
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0     68      0 --:--:-- --:--:-- --:--:--    68
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
100    64  100    64    0     0     27      0  0:00:02  0:00:02 --:--:--    27
│ ┌ Warning: platform_key() is deprecated, use platform_key_abi() from now on
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: Could not extract the platform key of https://dl.bintray.com/bstellato/generic/OSQP/0.5.0/osqp-0.5.0-mac64.tar.gz; continuing...
│ └ @ BinaryProvider /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/BinaryProvider/src/Prefix.jl:185
│ ERROR: LoadError: HTTP.ExceptionRequest.StatusError(401, HTTP.Messages.Response:
│ """
│ HTTP/1.1 401 Unauthorized
│ Server: nginx
│ Date: Mon, 22 Jul 2019 12:30:00 GMT
│ Content-Length: 0
│ Connection: keep-alive
│ 
│ """)
│ Stacktrace:
│  [1] #request#1 at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/ExceptionRequest.jl:22 [inlined]
│  [2] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Nothing) at ./none:0
│  [3] (::getfield(Base, Symbol("###48#49#50")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,getfield(CredentialsHandler, Symbol("##1#3")){String},Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}}, ::Function, ::Type, ::Vararg{Any,N} where N) at ./error.jl:231
│  [4] ##48#51 at ./none:0 [inlined]
│  [5] #request#1 at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/RetryRequest.jl:44 [inlined]
│  [6] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}, ::typeof(HTTP.request), ::Type{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Nothing) at ./none:0
│  [7] #request#1(::VersionNumber, ::String, ::Nothing, ::Function, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/MessageRequest.jl:47
│  [8] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}, ::typeof(HTTP.request), ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing) at ./none:0
│  [9] #request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Symbol,getfield(CredentialsHandler, Symbol("##1#3")){String},Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}}, ::Function, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/RedirectRequest.jl:24
│  [10] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}, ::typeof(HTTP.request), ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing) at ./none:0
│  [11] #request#5(::Base.Iterators.Pairs{Symbol,getfield(CredentialsHandler, Symbol("##1#3")){String},Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{getfield(CredentialsHandler, Symbol("##1#3")){String}}}}, ::Function, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Nothing) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/HTTP.jl:300
│  [12] #request at ./none:0 [inlined]
│  [13] #request#6 at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/HTTP.jl:314 [inlined]
│  [14] #request at ./none:0 [inlined]
│  [15] #open#7 at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/HTTP.jl:339 [inlined]
│  [16] open at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/HTTP/src/HTTP.jl:339 [inlined]
│  [17] download at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/CredentialsHandler/src/CredentialsHandler.jl:89 [inlined] (repeats 2 times)
│  [18] (::getfield(BinaryProvider.JuliaTeam, Symbol("##1#2")){getfield(BinaryProvider, Symbol("##49#72"))})(::String, ::String) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/BinaryProvider/src/JuliaTeam.jl:18
│  [19] #download#93(::Bool, ::Function, ::String, ::String) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/BinaryProvider/src/PlatformEngines.jl:494
│  [20] #download at ./none:0 [inlined]
│  [21] #download_verify#94(::Bool, ::Bool, ::Bool, ::Function, ::String, ::String, ::String) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/BinaryProvider/src/PlatformEngines.jl:595
│  [22] #download_verify at ./none:0 [inlined]
│  [23] #install#133(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/BinaryProvider/src/Prefix.jl:314
│  [24] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│  [25] top-level scope at /Users/liaoqiayuan/.juliapro/JuliaPro_v1.1.1.1/packages/OSQP/FaA6U/deps/build.jl:55
│  [26] include_relative(::Module, ::String) at /Applications/JuliaPro-1.1.1.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [27] include(::Module, ::String) at /Applications/JuliaPro-1.1.1.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│  [28] include(::String) at ./client.jl:403
│  [29] top-level scope at none:0
│ in expression starting at /Users/liaoqiayuan/.juliapro/JuliaPro_v1.1.1.1/packages/OSQP/FaA6U/deps/build.jl:48
└ @ Pkg.Operations /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.1.app/Contents/Resources/julia/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1138

**Comment by tkoolen** [comment]
Do you get the same error if you use plain Julia, not JuliaPro?

**Comment by QiayuanLiao** [comment]
> Do you get the same error if you use plain Julia, not JuliaPro?

wow! I try to use plain Julia and very things work well. Thanks!

**Comment by tkoolen** [comment]
Great. There are often problems with JuliaPro; JuliaPro pegs package versions, which isn't always a good thing (in this case, OSQP @ 0.5.0 while 0.5.2 was released a while ago already).

**Comment by QiayuanLiao** [comment]
I am building a open source quadruped use MPC. I have almost  finished the
low level (joint control, leg kinematic and dynamics.  I tried to use
python and pybullet to simulate the quadruped model and MPC. But it’s
impossible to use python to control the real robot because the slow speed.
And I have to rewrite all programs use c++.  I think Julia which can use no
only on simulation but also real-time control should be a very suitable
language of middle level control right?

Twan Koolen <notifications@github.com>于2019年7月23日 周二上午2:46写道：

**Comment by tkoolen** [comment]
That's a little off-topic for this issue, but feel free to ask questions over at https://discourse.julialang.org/.
